package cs321.create;

/**
 * GeneBankCreateBTreeArguments class represents the arguments required for creating a B-tree index from a DNA sequence file.
 */
public class GeneBankCreateBTreeArguments {
    private final boolean useCache;
    private final int degree;
    private final String gbkFileName;
    private final int subsequenceLength;
    private final int cacheSize;
    private final int debugLevel;

    /**
     * Constructor to initialize GeneBankCreateBTreeArguments.
     * @param useCache Whether to use cache.
     * @param degree Degree of the B-tree.
     * @param gbkFileName Path to the input DNA sequence file.
     * @param subsequenceLength Length of the DNA subsequence.
     * @param cacheSize Size of the cache (if caching is enabled).
     * @param debugLevel Debug level (0 for no debug, 1 for debug).
     */
    public GeneBankCreateBTreeArguments(boolean useCache, int degree, String gbkFileName, int subsequenceLength, int cacheSize, int debugLevel) {
        this.useCache = useCache;
        this.degree = degree;
        this.gbkFileName = gbkFileName;
        this.subsequenceLength = subsequenceLength;
        this.cacheSize = cacheSize;
        this.debugLevel = debugLevel;
    }

    @Override
    public boolean equals(Object obj)
    {
        //this method was generated using an IDE
        if (this == obj)
        {
            return true;
        }
        if (obj == null)
        {
            return false;
        }
        if (getClass() != obj.getClass())
        {
            return false;
        }
        GeneBankCreateBTreeArguments other = (GeneBankCreateBTreeArguments) obj;
        if (cacheSize != other.cacheSize)
        {
            return false;
        }
        if (debugLevel != other.debugLevel)
        {
            return false;
        }
        if (degree != other.degree)
        {
            return false;
        }
        if (gbkFileName == null)
        {
            if (other.gbkFileName != null)
            {
                return false;
            }
        }
        else
        {
            if (!gbkFileName.equals(other.gbkFileName))
            {
                return false;
            }
        }
        if (subsequenceLength != other.subsequenceLength)
        {
            return false;
        }
        if (useCache != other.useCache)
        {
            return false;
        }
        return true;
    }

    @Override
    public String toString()
    {
        //this method was generated using an IDE
        return "GeneBankCreateBTreeArguments{" +
                "useCache=" + useCache +
                ", degree=" + degree +
                ", gbkFileName='" + gbkFileName + '\'' +
                ", subsequenceLength=" + subsequenceLength +
                ", cacheSize=" + cacheSize +
                ", debugLevel=" + debugLevel +
                '}';
    }

    // Equals and toString methods generated by IDE
    // They are not documented as they are self-explanatory

    public boolean isUseCache() {
        return useCache;
    }

    public int getDegree() {
        return degree;
    }

    public String getGbkFileName() {
        return gbkFileName;
    }

    public int getSubsequenceLength() {
        return subsequenceLength;
    }

    public int getCacheSize() {
        return cacheSize;
    }

    public int getDebugLevel() {
        return debugLevel;
    }
}
